name: flutter_base_template
description: Flutter starter kit.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter

  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3

  # Models and Codegen
  equatable: ^2.0.5
  json_annotation: ^4.8.1

  # Service Locator & DI
  get_it: ^7.6.7
  injectable: ^2.3.2

  # State Management
  flutter_bloc: ^8.1.3

  # Navigation
  auto_route: ^7.8.4

  # Streams
  rxdart: ^0.27.7
  stream_transform: ^2.1.0

  # Logging
  logger: ^2.0.2+1
  sentry_flutter: ^7.14.0

  # UI and animations
  rive: ^0.12.4
  lottie: ^3.0.0
  flutter_svg: ^2.0.9

  # Fields and forms
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0

  # Misc
  url_launcher: ^6.2.1

  # Firebase
  firebase_auth: ^4.15.3
  firebase_core: ^2.23.0
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6

  # Web packages
  url_strategy: ^0.2.0
  responsive_framework: ^1.1.1

  # Graphs and data visualization
  syncfusion_flutter_core: ^23.1.44

  # Utils
  mocktail: ^1.0.3
  path_provider: ^2.1.2
  platform_info: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^3.0.1

  # Codegen
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2

  # Utils
  flutter_gen_runner: ^5.3.2
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
